import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import next from "ultracite/oxlint/next";
import react from "ultracite/oxlint/react";

export default defineConfig({
  ...core,
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    "**/node_modules/**",
    "**/.next/**",
    "**/.turbo/**",
    "**/convex/_generated/**",
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".conductor/**",
    ".context/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".github/agents/impeccable-*.agent.md",
    ".github/skills/impeccable/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".windsurf/**",
    "tools/oxlint/anti-slop/**",
  ],
  jsPlugins: [
    {
      name: "anti-slop",
      specifier: "./tools/oxlint/anti-slop/index.ts",
    },
  ],
  overrides: [
    ...(core.overrides ?? []),
    ...(react.overrides ?? []),
    ...(next.overrides ?? []),
    {
      files: ["packages/backend/convex/**/*.ts"],
      rules: { "unicorn/filename-case": "off" },
    },
  ],
  plugins: [
    ...(core.plugins ?? []),
    ...(react.plugins ?? []),
    ...(next.plugins ?? []),
  ],
  rules: {
    ...core.rules,
    ...react.rules,
    ...next.rules,
    "func-style": "off",
    "import/consistent-type-specifier-style": "off",
    "no-await-in-loop": "off",
    "no-nested-ternary": "off",
    "prefer-destructuring": "off",
    "react/button-has-type": "off",
    // Preserve the React Compiler opt-out after Oxlint split react-compiler.
    "react/capitalized-calls": "off",
    "react/error-boundaries": "off",
    "react/exhaustive-effect-dependencies": "off",
    "react/function-component-definition": "off",
    "react/globals": "off",
    "react/hooks": "off",
    "react/immutability": "off",
    "react/incompatible-library": "off",
    "react/invariant": "off",
    "react/memo-dependencies": "off",
    "react/no-deriving-state-in-effects": "off",
    "react/preserve-manual-memoization": "off",
    "react/purity": "off",
    "react/refs": "off",
    "react/rule-suppression": "off",
    "react/set-state-in-effect": "off",
    "react/set-state-in-render": "off",
    "react/static-components": "off",
    "react/syntax": "off",
    "react/todo": "off",
    "react/unsupported-syntax": "off",
    "react/use-memo": "off",
    "react/void-use-memo": "off",
    "require-await": "off",
    "sort-keys": "off",
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
    "typescript/consistent-type-definitions": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-await-expression-member": "off",
    "unicorn/no-document-cookie": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/prefer-export-from": "off",
  },
});
